# 1. Read the data

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [10]:
df_taxi = pd.read_excel("../data/taxi_dane.xlsx")

In [4]:
df_taxi.head(5)

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_latitude,pickup_longitude,pickup_location,dropoff_latitude,dropoff_longitude,dropoff_location,year,month
0,b57de4fbd42a4fcdfac294083ad896f9b3b19e30,1a0918b9bfea038d074d533672fa8d2a32a9b2628fbb34...,2013-10-01 00:00:00 UTC,2013-10-01 00:30:00 UTC,1800.0,1.49,NaN,NaN,32,out of town,31.45,0.0,0.0,5.5,36.95,Cash,no company name,"41,878865584","-87,625192142","POINT (-87,6251921424 41,8788655841)",NaN,NaN,NaN,2013,10
1,7e0b8a1d91467a8b6c38503812ccf9ceaf81ae46,2fea69c8a6e08471bc4339a05e9ee7955bef68d791f77a...,2013-10-01 00:00:00 UTC,2013-10-01 00:15:00 UTC,900.0,8.00,NaN,NaN,28,3,18.45,0.0,0.0,0.0,18.45,Cash,no company name,"41,874005383","-87,66351755","POINT (-87,6635175498 41,874005383)","41,96581197","-87,655878786","POINT (-87,6558787862 41,96581197)",2013,10
2,6f461021d891c897195a602bb6d0bc282f7cff30,061cabe01cfa6d1719184ef6316e77a21469d100eb70f1...,2013-10-01 00:15:00 UTC,2013-10-01 00:30:00 UTC,900.0,9.60,NaN,NaN,32,41,21.05,0.0,0.0,0.0,21.05,Cash,no company name,"41,878865584","-87,625192142","POINT (-87,6251921424 41,8788655841)","41,794090253","-87,592310855","POINT (-87,592310855 41,794090253)",2013,10
3,ad92e39b524db2e5ca7e54df5db96d806261ed66,fc662712fcee7cc17c53c79bb57f09d0a612440700aa67...,2013-10-01 00:15:00 UTC,2013-10-01 00:30:00 UTC,1620.0,0.49,1.703108e+10,1.703133e+10,8,33,16.25,0.0,0.0,1.0,17.25,Cash,no company name,"41,892507781","-87,626214906","POINT (-87,6262149064 41,8925077809)","41,859349715","-87,617358006","POINT (-87,6173580061 41,859349715)",2013,10
4,baf5ef44846907d5f0af6f0eb17ae25c784a80c0,873bacf70099d6c3eb461ab1946fcc8b47cfc95fe78c3b...,2013-10-01 00:30:00 UTC,2013-10-01 01:00:00 UTC,2220.0,32.50,NaN,NaN,8,out of town,61.45,0.0,0.0,0.0,61.45,Cash,no company name,"41,899602111","-87,633308037","POINT (-87,6333080367 41,899602111)",NaN,NaN,NaN,2013,10

# 2. Check basic data information

In [ ]:
null_before_data_type_conversion = df_taxi.isna().sum()
null_before_data_type_conversion

In [ ]:
# check number of rows and columns
df_taxi.shape

(100000, 25)

:

In [ ]:
# check column types
df_taxi.dtypes

unique_key                 object
taxi_id                    object
trip_start_timestamp       object
trip_end_timestamp         object
trip_seconds              float64
trip_miles                float64
pickup_census_tract       float64
dropoff_census_tract      float64
pickup_community_area      object
dropoff_community_area     object
fare                      float64
tips                      float64
tolls                     float64
extras                    float64
trip_total                float64
payment_type               object
company                    object
pickup_latitude            object
pickup_longitude           object
pickup_location            object
dropoff_latitude           object
dropoff_longitude          object
dropoff_location           object
year                        int64
month                       int64
dtype: object

:

- trip_start_timestamp, trip_end_timestamp: strings instead of datatype
- trip_seconds: string instead of a number, but these look like decimal type
- pickup_census_tract, dropoff_census_tract: scientific number, but stored as string
- pickup_community_area: these seem like numbers, but are stored as string
- dropoff_community_area: sometimes these are string but sometimes numbers
- pickup_latitude, pickup_longitude: these should be decimal numbers but are strings
- pickup_location: consists of 'POINT ' and then a pair of numbers in brackets. example: POINT (-87,6251921424 41,8788655841)
- dropoff_latitude, dropoff_longitude: should be number
- dropoff_location: consists of 'POINT ' and then a pair of numbers in brackets. example: POINT (-87,6251921424 41,8788655841)

In [ ]:


df_taxi['trip_start_timestamp'] = pd.to_datetime(df_taxi['trip_start_timestamp'])
df_taxi['trip_end_timestamp'] = pd.to_datetime(df_taxi['trip_end_timestamp'])

:

In [ ]:
df_taxi

,unique_key,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_latitude,pickup_longitude,pickup_location,dropoff_latitude,dropoff_longitude,dropoff_location,year,month
0,b57de4fbd42a4fcdfac294083ad896f9b3b19e30,1a0918b9bfea038d074d533672fa8d2a32a9b2628fbb34...,2013-10-01 00:00:00+00:00,2013-10-01 00:30:00+00:00,1800.0,1.49,NaN,NaN,32,out of town,31.45,0.00,0.0,5.5,36.95,Cash,no company name,"41,878865584","-87,625192142","POINT (-87,6251921424 41,8788655841)",NaN,NaN,NaN,2013,10
1,7e0b8a1d91467a8b6c38503812ccf9ceaf81ae46,2fea69c8a6e08471bc4339a05e9ee7955bef68d791f77a...,2013-10-01 00:00:00+00:00,2013-10-01 00:15:00+00:00,900.0,8.00,NaN,NaN,28,3,18.45,0.00,0.0,0.0,18.45,Cash,no company name,"41,874005383","-87,66351755","POINT (-87,6635175498 41,874005383)","41,96581197","-87,655878786","POINT (-87,6558787862 41,96581197)",2013,10
2,6f461021d891c897195a602bb6d0bc282f7cff30,061cabe01cfa6d1719184ef6316e77a21469d100eb70f1...,2013-10-01 00:15:00+00:00,2013-10-01 00:30:00+00:00,900.0,9.60,NaN,NaN,32,41,21.05,0.00,0.0,0.0,21.05,Cash,no company name,"41,878865584","-87,625192142","POINT (-87,6251921424 41,8788655841)","41,794090253","-87,592310855","POINT (-87,592310855 41,794090253)",2013,10
3,ad92e39b524db2e5ca7e54df5db96d806261ed66,fc662712fcee7cc17c53c79bb57f09d0a612440700aa67...,2013-10-01 00:15:00+00:00,2013-10-01 00:30:00+00:00,1620.0,0.49,1.703108e+10,1.703133e+10,8,33,16.25,0.00,0.0,1.0,17.25,Cash,no company name,"41,892507781","-87,626214906","POINT (-87,6262149064 41,8925077809)","41,859349715","-87,617358006","POINT (-87,6173580061 41,859349715)",2013,10
4,baf5ef44846907d5f0af6f0eb17ae25c784a80c0,873bacf70099d6c3eb461ab1946fcc8b47cfc95fe78c3b...,2013-10-01 00:30:00+00:00,2013-10-01 01:00:00+00:00,2220.0,32.50,NaN,NaN,8,out of town,61.45,0.00,0.0,0.0,61.45,Cash,no company name,"41,899602111","-87,633308037","POINT (-87,6333080367 41,899602111)",NaN,NaN,NaN,2013,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,5183ccee3fe7ce7614c051bce716cf77d65b6645,dade76fa1c7a36b5beb9e6af50e4e1592a94b6fcdcd58e...,2019-03-28 18:15:00+00:00,2019-03-28 18:30:00+00:00,1320.0,3.00,NaN,NaN,out of town,out of town,13.75,2.95,0.0,1.0,18.20,Credit Card,Sun Taxi,NaN,NaN,NaN,NaN,NaN,NaN,2019,3
99996,c98c6397a75a6c8f3fc572b7248acf76dafb6553,dade76fa1c7a36b5beb9e6af50e4e1592a94b6fcdcd58e...,2019-03-28 20:15:00+00:00,2019-03-28 20:45:00+00:00,1200.0,13.30,NaN,NaN,out of town,out of town,33.75,7.55,0.0,4.0,45.80,Credit Card,Sun Taxi,NaN,NaN,NaN,NaN,NaN,NaN,2019,3
99997,f69e05f976895f0f63ca044416bb6b0dfb31aa25,cde7992ca2a3bde11bce750fa6e3bbed7aa87ea83677cd...,2019-03-29 20:45:00+00:00,2019-03-29 21:00:00+00:00,445.0,1.17,NaN,NaN,out of town,out of town,6.50,2.00,0.0,0.0,9.00,Credit Card,Flash Cab,NaN,NaN,NaN,NaN,NaN,NaN,2019,3
99998,6006fb1785695d4e7ddfa999a617f39155062d21,eb0aa1f0dd78747ba0688bc786b87e037ed7bd33ecc4e1...,2019-03-30 16:15:00+00:00,2019-03-30 16:30:00+00:00,240.0,0.80,NaN,NaN,out of town,out of town,5.25,2.00,0.0,1.0,8.75,Credit Card,Medallion Leasin,NaN,NaN,NaN,NaN,NaN,NaN,2019,3
99999,3e396ce7ab1739ddc94ba9293a1983558e2ebc77,cde7992ca2a3bde11bce750fa6e3bbed7aa87ea83677cd...,2019-03-30 19:45:00+00:00,2019-03-30 20:00:00+00:00,839.0,1.73,NaN,NaN,out of town,out of town,9.25,0.00,0.0,0.0,9.25,Cash,Flash Cab,NaN,NaN,NaN,NaN,NaN,NaN,2019,3

: